In [2]:
import numpy as np
import pandas as pd

In [4]:
PATH = 'data/'

In [5]:
!ls {PATH}

kc_house_data.csv  kc_house_test_data.csv  kc_house_train_data.csv


In [8]:
train = pd.read_csv(f'{PATH}kc_house_train_data.csv', dtype= {'bathrooms':float, 'waterfront':int, 'sqft_above':int, 'sqft_living15':float, 'grade':int, 'yr_renovated':int, 'price':float, 'bedrooms':float, 'zipcode':str, 'long':float, 'sqft_lot15':float, 'sqft_living':float, 'floors':str, 'condition':int, 'lat':float, 'date':str, 'sqft_basement':int, 'yr_built':int, 'id':str, 'sqft_lot':int, 'view':int})

In [10]:
test = pd.read_csv(f'{PATH}kc_house_test_data.csv', dtype= {'bathrooms':float, 'waterfront':int, 'sqft_above':int, 'sqft_living15':float, 'grade':int, 'yr_renovated':int, 'price':float, 'bedrooms':float, 'zipcode':str, 'long':float, 'sqft_lot15':float, 'sqft_living':float, 'floors':str, 'condition':int, 'lat':float, 'date':str, 'sqft_basement':int, 'yr_built':int, 'id':str, 'sqft_lot':int, 'view':int})

In [23]:
train['bedrooms_squared'] = train['bedrooms']**2
train['bed_bath_rooms'] = train['bedrooms']*train['bathrooms']
train['log_sqft_living'] = np.log(train['sqft_living'])
train['lat_plus_long'] = train['lat']+train['long']

In [29]:
test['bedrooms_squared'] = test['bedrooms']**2
test['bed_bath_rooms'] = test['bedrooms']*test['bathrooms']
test['log_sqft_living'] = np.log(test['sqft_living'])
test['lat_plus_long'] = test['lat']+test['long']

In [36]:
for colname in ['bedrooms_squared','bed_bath_rooms','log_sqft_living','lat_plus_long']:
    print(round(test[colname].mean(),2))  #Ans 1

12.45
7.5
7.55
-74.65


In [42]:
from sklearn.linear_model import LinearRegression

In [44]:
model1_features = ['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long']
model2_features = ['sqft_living', 'bedrooms', 'bathrooms', 'lat','long','bed_bath_rooms']
model3_features = ['sqft_living', 'bedrooms', 'bathrooms', 'lat','long', 'bed_bath_rooms', 'bedrooms_squared', 'log_sqft_living','lat_plus_long']

In [45]:
reg1 = LinearRegression().fit(train[model1_features],train['price'])

In [46]:
reg2 = LinearRegression().fit(train[model2_features],train['price'])

In [47]:
reg3 = LinearRegression().fit(train[model3_features],train['price'])

In [50]:
reg1.coef_

array([ 3.12258646e+02, -5.95865332e+04,  1.57067421e+04,  6.58619264e+05,
       -3.09374351e+05])

In [51]:
reg2.coef_

array([ 3.06610053e+02, -1.13446368e+05, -7.14613083e+04,  6.54844630e+05,
       -2.94298969e+05,  2.55796520e+04])

In [52]:
reg3.coef_

array([ 5.29422820e+02,  3.45142296e+04,  6.70607813e+04,  5.34085611e+05,
       -4.06750711e+05, -8.57050439e+03, -6.78858667e+03, -5.61831484e+05,
        1.27334900e+05])

In [53]:
def rss(x,y): return ((x-y)**2).sum()

In [58]:
rss(reg1.predict(train[model1_features]),train['price'])

967879963049545.8

In [59]:
rss(reg2.predict(train[model2_features]),train['price'])

958419635074068.8

In [60]:
rss(reg3.predict(train[model3_features]),train['price'])

903436455050478.0

In [61]:
rss(reg1.predict(test[model1_features]),test['price'])

225500469795489.56

In [62]:
rss(reg2.predict(test[model2_features]),test['price'])

223377462976467.16

In [63]:
rss(reg3.predict(test[model3_features]),test['price'])

259236319207179.3